name: CI

on: [push]

jobs:
  tests:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        ruby: [2.4, 2.5, 2.6, 2.7]

    steps:
    - uses: actions/checkout@master

    - name: Sets up the Ruby version
      uses: actions/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}

    - name: Sets up the environment
      run: |
        sudo apt-get install libsqlite3-dev
        gem install -q bundler
        bundle install

    - name: Runs code QA and tests
      run: rspec

    - name: Publish to GPR
      continue-on-error: true
      if: ${{ github.ref == 'refs/heads/master' }}
      run: |
        mkdir -p $HOME/.gem
        touch $HOME/.gem/credentials
        chmod 0600 $HOME/.gem/credentials
        printf -- "---\n:github: Bearer ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
        gem build *.gemspec
        gem push --KEY github --host https://rubygems.pkg.github.com/${OWNER} *.gem
      env:
        GEM_HOST_API_KEY: ${{secrets.GPR_AUTH_TOKEN}}
        OWNER: fast_jsonapi
