name: CI

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        ruby: [2.4, 2.5, 2.6, 2.7]

    steps:
    - uses: actions/checkout@master

    - name: Sets up the Ruby version
      uses: actions/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}

    - name: Sets up the environment
      run: |
        sudo apt-get install libsqlite3-dev
        gem install -q bundler
        bundle install

    - name: Runs code QA and tests
      run: bundle exec rake

    - name: Publish to Rubygems
      continue-on-error: true
      if: ${{ github.ref == 'refs/heads/master' }}
      run: |
        mkdir -p $HOME/.gem
        touch $HOME/.gem/credentials
        chmod 0600 $HOME/.gem/credentials
        printf -- "---\n:rubygems_api_key: Bearer ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
        gem build *.gemspec
        gem push *.gem
      env:
        GEM_HOST_API_KEY: ${{secrets.RUBYGEMS_AUTH_TOKEN}}
